server:
  port: ${PORT:8080}
spring:
  application:
    name: gateway-ws
  cloud:
    gateway:
      routes:
      - id: userModule
        uri: lb://users-ws
        predicates:
        - Path=/users/**
        - Method=GET,PUT,POST
      - id: accountsModule
        uri: lb://accounts-ws
        predicates:
        - Path=/accounts/**
        - Method=GET,PUT,POST
      discovery:
        locator:
          lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka
