server:
  port: ${PORT:8080}
spring:
  application:
    name: gateway-ws
  cloud:
    gateway:
      routes:
        - id: users-ws-login
          uri: lb://users-ws
          predicates:
          - Path=/users-ws/users/login
          - Method=POST
          filters:
          - RemoveRequestHeader=Cookie
          - RewritePath=/users-ws/(?<segment>.*), /$\{segment}

        - id: users-ws-create
          uri: lb://users-ws
          predicates:
          - Path=/users-ws/users
          - Method=POST
          filters:
          - RemoveRequestHeader=Cookie
          - RewritePath=/users-ws/(?<segment>.*), /$\{segment}

        - id: users-ws-status-check
          uri: lb://users-ws
          predicates:
          - Path=/users-ws/users/status/check
          - Method=GET
          - Header=Authorization, Bearer (.*)
          filters:
          - RemoveRequestHeader=Cookie
          - JwtTokenValidationFilter
          - RewritePath=/users-ws/(?<segment>.*), /$\{segment}

        - id: users-ws-put-delete
          uri: lb://users-ws
          predicates:
          - Path=/users-ws/users/**
          - Method=GET,PUT,DELETE
          - Header=Authorization, Bearer (.*)
          filters:
          - RemoveRequestHeader=Cookie
          - JwtTokenValidationFilter
          - RewritePath=/users-ws/(?<segment>.*), /$\{segment}

        - id: accountsModule
          uri: lb://accounts-ws
          predicates:
          - Path=/accounts-ws/**
          - Method=GET,PUT,POST
          filters:
          - RemoveRequestHeader=Cookie
          - RewritePath=/accounts-ws/(?<segment>.*), /$\{segment}

      discovery:
        locator:
          lower-case-service-id: true
  devtools:
    restart:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka
management:
  endpoints:
    web:
      exposure:
        include: "*"
info:
  app:
    name: @project.artifactId@
    version: @project.version@
    encoding: @project.build.sourceEncoding@
    java:
      source: @java.version@
      target: @java.version@
