
server:
  port: ${PORT:8080}

info:
  app:
    name: @project.artifactId@
    version: @project.version@
    encoding: @project.build.sourceEncoding@
    java:
      source: @java.version@
      target: @java.version@
    developer:
      name: Amsidh Lokhande
      emailId: amsidhlokhande@gmail.com

spring:
  application:
    name: gateway-ws
  cloud:
    gateway:
      routes:
        - id: users-ws-login
          uri: lb://users-ws
          predicates:
          - Path=/users-ws/users/login
          - Method=POST
          filters:
          - RemoveRequestHeader=Cookie
          - RewritePath=/users-ws/(?<segment>.*), /$\{segment}

        - id: users-ws-create
          uri: lb://users-ws
          predicates:
          - Path=/users-ws/users
          - Method=POST
          filters:
          - RemoveRequestHeader=Cookie
          - RewritePath=/users-ws/(?<segment>.*), /$\{segment}

        - id: users-ws-status-check
          uri: lb://users-ws
          predicates:
          - Path=/users-ws/users/status/check
          - Method=GET
          - Header=Authorization, Bearer (.*)
          filters:
          - RemoveRequestHeader=Cookie
          - AuthorizationFilter
          - RewritePath=/users-ws/(?<segment>.*), /$\{segment}

        - id: users-ws-put-delete
          uri: lb://users-ws
          predicates:
          - Path=/users-ws/users/**
          - Method=GET,PUT,DELETE
          - Header=Authorization, Bearer (.*)
          filters:
          - RemoveRequestHeader=Cookie
          - AuthorizationFilter
          - RewritePath=/users-ws/(?<segment>.*), /$\{segment}

        - id: users-ws-h2-console
          uri: lb://users-ws
          predicates:
            - Path=/users-ws/h2-console/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/users-ws/(?<segment>.*), /$\{segment}

        - id: users-ws-swagger-ui
          uri: lb://users-ws
          predicates:
            - Path=/users-ws/swagger-ui.html,/users-ws/actuator/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/users-ws/(?<segment>.*), /$\{segment}

        - id: accountsModule
          uri: lb://accounts-ws
          predicates:
          - Path=/accounts-ws/**
          - Method=GET,PUT,POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/accounts-ws/(?<segment>.*), /$\{segment}

        - id: albums-ws-get-albums-user
          uri: lb://albums-ws
          predicates:
            - Path=Path=/albums-ws/users/{segment}/albums
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/albums-ws/(?<segment>.*), /$\{segment}

#Moved to central config location gateway-ws.properties file
#      discovery:
#        locator:
#          lower-case-service-id: true

#Moved to central config server application.properties
#Devtool Properties
#  devtools:
#    restart:
#      enabled: true

  config:
    import: optional:configserver:http://localhost:8888

#Moved to central config server location application.properties
#RabbitMQ Configuration
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: admin
#    password: admin

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8010/eureka

#jwt:
#  secret:
#    salt: kjv7idh68jfd7bd7v68v6avv%v9$v78#vkdfshg
