server:
  port: ${PORT:8080}
spring:
  application:
    name: gateway-ws
  cloud:
    gateway:
      routes:
      - id: userModule
        uri: lb://users-ws
        predicates:
        - Path=/users-ws/**
        - Method=GET,PUT,POST
        filters:
        - RemoveRequestHeader=Cookie
        - RewritePath=/users-ws/(?<segment>.*), /$\{segment}

      - id: accountsModule
        uri: lb://accounts-ws
        predicates:
        - Path=/accounts-ws/**
        - Method=GET,PUT,POST
        filters:
        - RemoveRequestHeader=Cookie
        - RewritePath=/accounts-ws/(?<segment>.*), /$\{segment}
      discovery:
        locator:
          lower-case-service-id: true
  devtools:
    restart:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka
management:
  endpoints:
    web:
      exposure:
        include: "*"
info:
  app:
    name: @project.artifactId@
    version: @project.version@
    encoding: @project.build.sourceEncoding@
    java:
      source: @java.version@
      target: @java.version@
